

- name: updating packages repo in debian
  apt:
    update_cache: yes

- name: Install nginx on debian
  apt:
    name: "{{ packages }}"
    state: "{{ version }}"
    # force: yes
    # autoclean: yes
    #run_once: yes
  notify: Start service
  become: yes
  tags: installation
  





